const sidebars = {
  comedy: [
    "intro",

    {
      type: 'category',
      label: '✝️ Christianity',
      items: [
        "comedy/christianity-mary",
        "comedy/christianity-saint-peter",
        "comedy/christianity-john",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },

    {
      type: 'category',
      label: '📜 Historical Figures',
      items: [
        "comedy/historical-figures-franklin",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },


    {
      type: 'category',
      label: '🍴 Cooking',
      items: [
        "comedy/cooking-curry",
        "comedy/cooking-bread",
        "comedy/cooking-yakiniku",
        "comedy/cooking-potato-memories",
        "comedy/cooking-ramen",
        "comedy/cooking-sushi-nightmare",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },

    {
      type: 'category',
      label: '🚑 Incident',
      items: [
        "comedy/incident-shiretoko",
        "comedy/incident-hakkoda",
        "comedy/incident-sewol",
        "comedy/incident-everest",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },

    {
      type: 'category',
      label: '🔭 Planet',
      items: [
        "comedy/planet-mercury",
        "comedy/planet-mars",
        "comedy/planet-pluto",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },

    {
      type: 'category',
      label: '📚 grammar',
      items: [
        "comedy/grammar-past-subjunctive",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",
        //"comedy/incident-",                   
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
        //"",
      ],
      collapsed: false,
    },

  ],
};

module.exports = sidebars;
